version: "3.10"

services:
  django:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - blazegraph
    environment:
      - BLAZEGRAPH_URL=http://blazegraph:8080/bigdata

  blazegraph:
    image: blazegraph/blazegraph:latest
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx4g
    volumes:
      - blazegraph-data:/blazegraph/data

volumes:
  blazegraph-data:
