version: "3.10"

services:
  django:
    build: ./backend/graphdb_project
    ports:
      - "8889:9999"
    depends_on:
      - blazegraph
    environment:
      - BLAZEGRAPH_URL=http://blazegraph:8080/bigdata

  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx4g
    volumes:
      - blazegraph-data:/blazegraph/data

volumes:
  blazegraph-data:
